name: Clojure CI - Unit and Integration Tests

on: [ push, pull_request ]

jobs:
  test:
    name: Running Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: lein deps
      - name: Run tests
        run: lein test
      - name: Archive production artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            tmp
